name = "tremorsi-agenda"
main = "src/index.js"
compatibility_date = "2026-08-01"

routes = [
  { pattern = "agenda.tremorsi.com", custom_domain = true }
]

[[kv_namespaces]]
binding = "AGENDA"
id = "0ea9ff300af54ffc8c46d4bd5f63325a"
